name: python-challenge
on: push
jobs:
  python-test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
        with:
          repository: stella-0428/challenge3
          ref: main
          path: python
      - name: setting up the python env
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: installing tools for python
        run: python -m pip install flake8
      - name: running the lint test
        run: flake8 python/
  upload-artifact:
    runs-on: ubuntu-latest
    needs: [python-test]
    steps:
      - name: checkout code
        uses: actions/checkout@v4
        with:
          repository: stella-0428/challenge3
          ref: main
          path: python
      - name: upload to atrifact
        uses: actions/upload-artifact@v4
        with: 
          repository: stella-0428/challenge3
          ref: main
          path: artifact
    
             
        
          
        
          
